display:
  default:
    display_title: Huvud
    display_options:
      pager:
        options:
          tags:
            next: 'nästa ›'
            previous: '‹ föregående'
            first: '« första'
            last: 'sista »'
          expose:
            items_per_page_label: 'Inlägg per sida'
            items_per_page_options_all_label: '- Alla -'
      exposed_form:
        options:
          submit_button: Verkställ
          reset_button_label: Återställ
          exposed_sorts_label: 'Sortera efter'
  page_1:
    display_title: Sida
  feed_1:
    display_title: Innehållsflöde
