label: Filer
display:
  default:
    display_title: Huvud
    display_options:
      title: Filer
      fields:
        filename:
          label: Namn
        filemime:
          label: 'Typ av MIME'
        filesize:
          label: Storlek
        status:
          label: Status
        timestamp:
          label: 'Datum för uppladdning'
        count:
          label: 'Används i'
      pager:
        options:
          tags:
            next: 'nästa ›'
            previous: '‹ föregående'
          expose:
            items_per_page_label: 'Inlägg per sida'
            items_per_page_options_all_label: '- Alla -'
      exposed_form:
        options:
          submit_button: Filtrera
          reset_button_label: Återställ
          exposed_sorts_label: 'Sortera efter'
      filters:
        filename:
          expose:
            label: Filnamn
        filemime:
          expose:
            label: 'Typ av MIME'
        status:
          expose:
            label: Status
  page_1:
    display_options:
      menu:
        title: Filer
  page_2:
    display_options:
      fields:
        entity_label:
          label: Entitet
        type:
          label: Objektstyp
        count:
          label: 'Antal använd'
      pager:
        options:
          tags:
            next: 'nästa ›'
            previous: '‹ föregående'
          expose:
            items_per_page_label: 'Inlägg per sida'
            items_per_page_options_all_label: '- Alla -'
      arguments:
        fid:
          exception:
            title: Alla
