description: 'Hitta och hantera innehåll.'
label: Innehåll
display:
  default:
    display_title: Huvud
    display_options:
      title: Innehåll
      fields:
        title:
          label: Titel
        name:
          label: Författare
        status:
          label: Status
        changed:
          label: Uppdaterad
        dropbutton:
          label: Funktioner
        timestamp:
          label: 'Har nytt innehåll'
      exposed_form:
        options:
          submit_button: Filtrera
          reset_button_label: Återställ
          exposed_sorts_label: 'Sortera efter'
      empty:
        area_text_custom:
          content: 'Inget innehåll tillgängligt.'
      filters:
        status:
          expose:
            label: Status
        type:
          expose:
            label: Typ
        langcode:
          expose:
            label: Språk
  page_1:
    display_title: Sida
    display_options:
      menu:
        title: Innehåll
      tab_options:
        title: Innehåll
