admin_role: administrator
anonymous: Gäst
verify_mail: 0
notify:
  cancel_confirm: true
  password_reset: true
  status_activated: 1
  status_blocked: 0
  status_cancelled: false
  register_admin_created: true
  register_no_approval_required: true
  register_pending_approval: true
  status_canceled: 0
register: admin_only
signatures: 0
cancel_method: user_cancel_block
password_reset_timeout: 86400
password_strength: 1
langcode: en
